---
- name: Include role Centos
  include: centos.yml
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "CentOS"

- name: Include role Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
...